# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Philip Meyerdierks
title: Full Stack Webdeveloper
email: philip@myrdrks.de
website: myrdrks.de

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: myrdrks
github_username:  myrdrks
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: myrdrks
linkedin_username: philip-meyerdierks-476a0392
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: myrdrks.de
  icon: fas fa-globe
  url: https://www.myrdrks.de
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Philip. I am a full stack web developer in my mid-thirties residing in Bremen, Germany.
  Over time, I have developed an extensive skill set that continues to grow. Here's a summary starting from foundational skills:
  - Hosting servers and managing server software
  - Creating secure network routes
  - Designing and implementing database architectures
  - Orchestrating containers for application deployment
  - Configuring webservers and proxies
  - Crafting business logic to meet specific requirements
  - Developing back end systems for web applications
  - Implementing interfaces through APIs
  - Designing user interfaces with a focus on usability and aesthetic appeal
  - Ensuring customer needs are met and providing an excellent user experience

  Below is a list of some of my favorite tools, frameworks, and libraries:

  <mark>React</mark> <mark>TypeScript</mark> <mark>NestJS</mark> <mark>GraphQL</mark> <mark>Svelte</mark> <mark>Vue</mark> <mark>Nginx</mark> <mark>Node.js</mark> <mark>MongoDB</mark> <mark>MySQL</mark> <mark>Remix</mark> <mark>Docker</mark> <mark>Proxmox</mark> <mark>AWS</mark> <mark>MQTT</mark> <mark>Adobe XD</mark> <mark>PostgreSQL</mark>

  As technology advances, I continuously learn and adapt to ensure I provide the best solutions to the challenges at hand.
content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: r&r GmbH Bremen
        link: rr-bremen.de
        # link_text: boringcompany.com
        sub_title: Full stack webdeveloper
        caption: June 2013 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          I initiated my web development career at this esteemed company, rapidly progressing over nearly a decade from novice to expert.

          Previously trained as a photographer, I found photography opportunities dwindling as the company branched into new business sectors. To adapt, I independently learned JavaScript and PHP, expanding my skill set to accommodate the changing landscape.

          My newfound skills were put to test in a pilot project with a long-standing client, providing a favorable environment for practical application and growth. Despite a generous deadline, the successful completion of the project brought satisfaction to both the client and myself.

          Today, we work closely with our clients to develop tailored web-based software solutions, primarily serving B2B needs like digital asset management, approval processes, and other business functions.  
  
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Professional training as a photographer
        caption: 2010 - 2013
        sub_title: r&r GmbH Bremen
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          In 2010 I started a professional training as a photographer at a small photostudio for portraits and advertising near Bremen.
          I soon realized that taking photos of people is not my biggest skill. So I focused on product and advertisement photography. In 2013 I successfully graduated.
  
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Boating
      - Geocaching
      - 3D Printing
      - Home Automation
      - Voluntary Work at [Kinder- und Jugendförderverein Platjenwerbe e.V.](https://kijuv.de) & [Heimatverein Platjenwerbe e.V.](https://hv-platjenwerbe.de)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
