# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Philip Meyerdierks
title: Full Stack Webdeveloper
email: philip.meyerdierks@gmail.com
website: www.myrdrks.de

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: myrdrks
github_username:  myrdrks
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: myrdrks
linkedin_username: philip-meyerdierks-476a0392
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hej, my name is Philip, I'm a 34 years old full stack webdeveloper from Bremen, Germany.
  As a full stack developer my set of skills is long and is getting even longer with the time.
  So let's start from the bottom:
  - Hosting servers
  - Manage & maintain server software
  - Routing networks
  - Creating & designing database architechtures
  - Orchestrate containers
  - Setting up webservers and proxys
  - Creating business logics
  - Developing back ends
  - Applying action layers & APIs
  - Designing user interfaces
  - Complete everything with customers needs and user experience

  These are my favorite tools, frameworks & librarys (unsorted list):

  <mark>React</mark> <mark>Meteor</mark> <mark>Express</mark> <mark>GraphQL</mark> <mark>Svelte</mark> <mark>Vue</mark> <mark>Nginx</mark> <mark>Node.js</mark> <mark>MongoDB</mark> <mark>MySQL</mark> <mark>Remix</mark> <mark>Svelte</mark>

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: r&r GmbH Bremen
        link: rr-bremen.de
        # link_text: boringcompany.com
        sub_title: Full stack webdeveloper
        caption: June 2013 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            At this lovely company I started my career as a webdeveloper. From zero to the moon in very short (almost 10 years now) time.
            
            But before that I ended my professional training as a photographer here. My colleagues discovered new business fields and photography jobs were rare sometimes. So I learned JavaScript and PHP by myself to fit into the new business fields.
            
            So we started a pilot project with a longtime customer who trusts us, where I could test my skills. Luckily the project had a very graceful deadline. But in the end the customer was happy and so was I.
            
            Now we develop very close to our customers special web based software to fit their needs.
            
            Most of the work is for b2b purposes like digital asset management, approval processes & other business stuff.
  
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Professional training as a photographer
        caption: 2010 - 2013
        sub_title: r&r GmbH Bremen
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          In 2010 I started a professional training as a photographer at a small photostudio for portraits and advertising near Bremen.
          I soon realized that taking photos of people is not my biggest skill. So I focused on product and advertisement photography. In 2013 I successfully graduated.
  
  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
